/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'blue-main': '#0666e2',
        'blue-light': '#ebf2ff',
        'blue-dark': '#0058ca',
        dark: '#24243a',
        'dark-dark1': '#172849',
        'dark-dark2': '#101e36',
        'dark-dark-button': '#404b65',
        grey3: '#838aa4',
        grey2: '#c3cbdf',
        grey1: '#f5f6f8',
        white: '#ffffff',
        red: '#d91404',
        green: '#7bb51e',
        'red-light': '#f8e5e4',
        'green-light': '#e9f8e7',
        'grey-active': '#f1f3f8',
        'dark-grey4': '#5a709c',
        'dark-white': '#fafafa',
        'dark-orange': '#e94d2b',
        'dark-orange-light': '#e09e6d',
        'dark-blue': '#0666e2',
        'dark-blue-light': '#579ef9',
        'dark-green': '#3fa96a',
        'dark-green-light': '#3fa96a',
        'dark-closed': '#273654',
        'dark-closed-light': '#8b9fc7',
        'dark-history-hover': '#152643',
        'dark-active': '#3a5281',
        'dark-disable': '#182947',
        'dark-input': '#4c556b',
        'dark-red': '#e0473a',
        'page-bg': 'var(--page-bg)',
        active: '#b9221c',
        'disabled-icon': '#b9221c',
        wrap: 'var(--wrap-bg)',
        form: 'var(--form-bg)',
        'modal-bg': 'var(--modal-bg)',
        'dark-blue-0.25': 'color-mix(in srgb, #0666e2, transparent 75%)',
        'dark-green-0.25': 'color-mix(in srgb, #3fa96a, transparent 75%)',
        'dark-orange-0.25': 'color-mix(in srgb, #e94d2b, transparent 75%)',
        'blue-ai-room-timer': '#e3f5ff',
        'room-tools-panel-bg': '#0b152940',
      },
      boxShadow: {
        'dark-bold': '0 4px 12px rgba(16, 9, 8, 1.0)',
        'dark-medium': '0px 4px 12px var(--shadow)',
      },
      gridTemplateColumns: {
        'questions-list': '1.5rem auto 1.125rem',
        'settings-list': '9.25rem auto',
      },
    },
  },
  plugins: [],
};
