import { LocalizationLang } from './context/LocalizationContext';

export const enum LocalizationKey {
  HighlightsRoomsPageName,
  CurrentRoomsPageName,
  ClosedRoomsPageName,
  QuestionsPageName,
  CategoriesPageName,
  RoomReviewPageName,
  CandidateOpinion,
  CandidateMarks,
  DoNotRate,
  Page,
  LogOut,
  Edit,
  Viewer,
  Expert,
  Examinee,
  Save,
  Saved,
  CreateQuestion,
  EditQuestion,
  QuestionText,
  QuestionType,
  QuestionTypePublic,
  QuestionTypePrivate,
  QuestionCodeEditor,
  QuestionAddCodeEditor,
  QuestionRemoveCodeEditor,
  QuestionAnswerOptionDefaultName,
  QuestionAnswerOptions,
  QuestionAddAnswerOption,
  QuestionDeleteAnswerOption,
  QuestionAnswerOptionName,
  CreateCategory,
  CategoryName,
  CategoryParent,
  CategoryOrder,
  Create,
  Continue,
  Cancel,
  Close,
  CloselWithoutSave,
  Stay,
  Error,
  Loading,
  NotSelected,
  QuestionCreatedSuccessfully,
  QuestionUpdatedSuccessfully,
  CategoryCreatedSuccessfully,
  CategoryUpdatedSuccessfully,
  LoadingRoom,
  ErrorLoadingRoom,
  ErrorLoadingRoomState,
  ErrorSendingActiveQuestion,
  ReactionsLoadingError,
  ErrorSendingReaction,
  TermsOfUsageAcceptance,
  TermsOfUsage,
  Login,
  CloseRoom,
  CloseRoomWithoutReview,
  StartRoom,
  StartReviewRoom,
  StartReviewRoomModalTitle,
  Yes,
  No,
  RoomStatusNew,
  RoomStatusActive,
  RoomStatusReview,
  RoomStatusClose,
  RoomStatusExpire,
  TagsLoading,
  NoTags,
  BuildHash,
  CreateRoom,
  NewRoom,
  EditRoom,
  CreateRoomStep1,
  CreateRoomStep2,
  RoomName,
  RoomNamePrompt,
  RoomDateAndTime,
  RoomQuestions,
  RoomSelectedQuestions,
  RoomDuration,
  AddRoomQuestions,
  RoomParticipants,
  SearchByValue,
  UserStreamError,
  ChatWelcomeMessage,
  ChatWelcomeMessageNickname,
  ChatMessagePlaceholder,
  SearchByName,
  RootCategories,
  Category,
  Subcategory,
  SelectCategorySubcategory,
  CallRecording,
  Archive,
  ArchiveLoading,
  Unarchive,
  UnarchiveLoading,
  NoQuestionsSelector,
  Join,
  JoiningRoom,
  SetupDevices,
  Settings,
  Chat,
  Exit,
  Theme,
  ThemeSystem,
  ThemeLight,
  ThemeDark,
  Language,
  PleaseSelectRecognitionLanguage,
  RecognitionLanguage,
  You,
  NoRecords,
  ConnectionError,
  RoomConnectionError,
  LocalizationLangEn,
  LocalizationLangRu,
  AiAssistantName,
  ErrorApplyRoomInvite,
  RoomInvitesLoading,
  Invitations,
  InviteViaLink,
  RefreshAll,
  NextRoomQuestion,
  CopiedToClipboard,
  Of,
  RoomQuestionEvaluationTitle,
  SaveRoomQuestionEvaluationWarningLine1,
  SaveRoomQuestionEvaluationWarningLine2,
  CloseRoomWithoutQuestionEvaluationWarningLine1,
  CloseRoomWithoutQuestionEvaluationWarningLine2,
  MarksGroupBad,
  MarksGroupMedium,
  MarksGroupGood,
  MarksGroupPerfect,
  NotFound,
  AverageCandidateMark,
  MarksForQuestions,
  OpinionsAndMarks,
  QuestionAnswerDetails,
  EmptyRoomNameError,
  EmptyRoomQuestionTreeError,
  RoomEmptyStartTimeError,
  RoomStartTimeMustBeGreaterError,
  RoomEmptyQuestionsListError,
  InterviewHistoryTitle,
  RoomReviewSave,
  RoomReviewWaiting,
  EmptyCommentQuestionEvaluation,
  QurstionTranscription,
  QuestionCode,
  AnswerCode,
  WeAwareOfProblem,
  CurrentQuestionNotBeSaved,
  CurrentRoomNotBeSaved,
  LoadingAccountError,
  LoadingAccountErrorTitle,
  Opinions,
  Transcription,
  CompleteAndEvaluateCandidate,
  CategoriesArchive,
  QuestionsArchive,
  WaitingInterviewStart,
  RoomStartDescription,
  NoData,
  UserConnectedToRoom,
  NotEnoughRights,
  WebcamBackgroundBlur,
  Feedback,
  RateMeDescription,
  RateMeCommands,
  LetsBeginDescription,
  LetsBeginCommand,
  HomeDescription,
  QuestionTreesPageName,
  CreateQuestionTree,
  QuestionTree,
  QuestionTreeName,
  QuestionTreeNodeDelete,
  QuestionTreeNodeNewItemBelow,
  QuestionTreeNodeNewItemInside,
  QuestionTreeNodeMoveUp,
  QuestionTreeNodeMoveDown,
  QuestionTreeNodeMoveLeft,
  QuestionTreeNodeMoveRight,
  QuestionTreeCreatedSuccessfully,
  QuestionTreeUpdatedSuccessfully,
  QuestionTreeExpandAll,
  QuestionTreeCollapseAll,
  QuestionTreeRootNode,
  From10,
  AnswerEvaluation,
  ExampleOfCorrectAnswer,
  Test,
  Run,
  ExpectsExecuteResults,
  ExpectsExecuteInput,
  ExpectsExecuteOutput,
  ExpectsExecuteOutputExpected,
  ExpectsExecuteResultsPassed,
  ExpectsExecuteResultsNotPassed,
  ExecutionResultsSubmit,
  Completed,
  MeetingBeingRecorded,
  NewNotifications,
  NoNewNotifications,
  Clear,
  AnswerAgain,
  RoadmapsPageName,
  RoadmapsPageDescription,
  RoadmapsArchivePageName,
  RoadmapCreatePageName,
  RoadmapYourProgress,
  RoadmapLevel0,
  RoadmapLevel1,
  RoadmapLevel2,
  RoadmapLevel3,
  RoadmapToFinish,
  HomeInfoTitle,
  HomeInfoTheoryBlockTitle,
  HomeInfoTheoryBlockInfo,
  HomeInfoCodingBlockTitle,
  HomeInfoCodingBlockInfo,
  HomeInfoPricingTitle,
  HomeInfoPricingFree,
  HomeInfoPricingPoint1,
  HomeInfoPricingPoint2,
  StartAnswer,
  Learn,
  ErrorRecognitionNotSupportedTitle,
  ErrorRecognitionNotSupportedDescription,
  BusinessAnalyticPageName,
  AllowAccessToMicrophone,
  AllowAccessToMicrophoneDescription,
  TextAnswer,
  SendAnswer,
  StartInterview,
  Preview,
  SkipQuestion,
}

export const LocalizationCaptions: Record<
  LocalizationLang,
  Record<LocalizationKey, string>
> = {
  [LocalizationLang.en]: {
    [LocalizationKey.HighlightsRoomsPageName]: 'Rooms',
    [LocalizationKey.CurrentRoomsPageName]: 'Current rooms',
    [LocalizationKey.ClosedRoomsPageName]: 'Closed rooms',
    [LocalizationKey.QuestionsPageName]: 'Questions',
    [LocalizationKey.CategoriesPageName]: 'Categories',
    [LocalizationKey.RoomReviewPageName]: 'Interview results',
    [LocalizationKey.CandidateOpinion]: 'Your opinion about candidate',
    [LocalizationKey.CandidateMarks]:
      'Your assessments of the candidate and comments on questions',
    [LocalizationKey.DoNotRate]: 'Do not rate',
    [LocalizationKey.Page]: 'Page',
    [LocalizationKey.LogOut]: 'Logout',
    [LocalizationKey.Edit]: 'Edit',
    [LocalizationKey.Viewer]: 'Viewer',
    [LocalizationKey.Expert]: 'Expert',
    [LocalizationKey.Examinee]: 'Examinee',
    [LocalizationKey.Save]: 'Save',
    [LocalizationKey.Saved]: 'Saved',
    [LocalizationKey.CreateQuestion]: 'Creating question',
    [LocalizationKey.EditQuestion]: 'Editing question',
    [LocalizationKey.QuestionText]: 'Text',
    [LocalizationKey.QuestionType]: 'Type',
    [LocalizationKey.QuestionTypePrivate]: 'Private',
    [LocalizationKey.QuestionCodeEditor]: 'Question code',
    [LocalizationKey.QuestionAddCodeEditor]: 'Add question code',
    [LocalizationKey.QuestionRemoveCodeEditor]: 'Remove code',
    [LocalizationKey.QuestionAnswerOptionDefaultName]: 'Answer',
    [LocalizationKey.QuestionAnswerOptions]: 'Answer options',
    [LocalizationKey.QuestionAddAnswerOption]: 'Add answer option',
    [LocalizationKey.QuestionDeleteAnswerOption]: 'Delete answer option',
    [LocalizationKey.QuestionAnswerOptionName]: 'Answer option name',
    [LocalizationKey.QuestionTypePublic]: 'Public',
    [LocalizationKey.CreateCategory]: 'Create category',
    [LocalizationKey.CategoryName]: 'Category name',
    [LocalizationKey.CategoryParent]: 'Category parent',
    [LocalizationKey.CategoryOrder]: 'Category order',
    [LocalizationKey.Create]: 'Create',
    [LocalizationKey.Continue]: 'Continue',
    [LocalizationKey.Cancel]: 'Cancel',
    [LocalizationKey.Close]: 'Close',
    [LocalizationKey.CloselWithoutSave]: 'Exit without saving',
    [LocalizationKey.Stay]: 'Stay',
    [LocalizationKey.Error]: 'Error',
    [LocalizationKey.Loading]: 'Loading',
    [LocalizationKey.NotSelected]: 'Not selected',
    [LocalizationKey.QuestionCreatedSuccessfully]:
      'Question created successfully',
    [LocalizationKey.QuestionUpdatedSuccessfully]:
      'Question updated successfully',
    [LocalizationKey.CategoryCreatedSuccessfully]:
      'Category created successfully',
    [LocalizationKey.CategoryUpdatedSuccessfully]:
      'Category updated successfully',
    [LocalizationKey.LoadingRoom]: 'Loading meeting',
    [LocalizationKey.ErrorLoadingRoom]: 'Error loading meeting',
    [LocalizationKey.ErrorLoadingRoomState]: 'Error loading meeting state',
    [LocalizationKey.ErrorSendingActiveQuestion]:
      'Error sending current question',
    [LocalizationKey.ReactionsLoadingError]: 'Reactions loading error',
    [LocalizationKey.ErrorSendingReaction]: 'Error sending reaction',
    [LocalizationKey.TermsOfUsageAcceptance]:
      'By login, you acknowledge that you have read,\nunderstood, and agree to ',
    [LocalizationKey.TermsOfUsage]: 'Terms of usage',
    [LocalizationKey.Login]: 'Login',
    [LocalizationKey.CloseRoom]: 'Close meeting',
    [LocalizationKey.CloseRoomWithoutReview]:
      'Close meeting without waiting for evaluations',
    [LocalizationKey.StartRoom]: 'Start interview',
    [LocalizationKey.StartReviewRoom]: 'Start meeting review.',
    [LocalizationKey.StartReviewRoomModalTitle]:
      'Start filling out meeting report?',
    [LocalizationKey.Yes]: 'Yes ✔️',
    [LocalizationKey.No]: 'No ❌',
    [LocalizationKey.RoomStatusNew]: 'Waiting to start',
    [LocalizationKey.RoomStatusActive]: 'Active',
    [LocalizationKey.RoomStatusReview]: 'Review',
    [LocalizationKey.RoomStatusClose]: 'Close',
    [LocalizationKey.RoomStatusExpire]: 'Expire',
    [LocalizationKey.TagsLoading]: 'Loading tags',
    [LocalizationKey.NoTags]: 'No tags',
    [LocalizationKey.BuildHash]: 'Build',
    [LocalizationKey.CreateRoom]: 'Create meeting',
    [LocalizationKey.NewRoom]: 'New room',
    [LocalizationKey.EditRoom]: 'Editing room',
    [LocalizationKey.CreateRoomStep1]: 'Step 1 - Filling the Room',
    [LocalizationKey.CreateRoomStep2]: 'Step 2 - Inviting Participants',
    [LocalizationKey.RoomName]: 'Meeting name',
    [LocalizationKey.RoomNamePrompt]:
      'In the title, indicate the name of the candidate and the position for which the interview will be held',
    [LocalizationKey.RoomDateAndTime]: 'Date and time',
    [LocalizationKey.RoomQuestions]: 'Questions list',
    [LocalizationKey.RoomSelectedQuestions]: 'Selected questions',
    [LocalizationKey.RoomDuration]: 'Duration',
    [LocalizationKey.AddRoomQuestions]: 'Add questions',
    [LocalizationKey.RoomParticipants]: 'Participants',
    [LocalizationKey.SearchByValue]: 'Search by value',
    [LocalizationKey.UserStreamError]: 'Unable to access camera and microphone',
    [LocalizationKey.ChatWelcomeMessage]: 'Welcome to chat',
    [LocalizationKey.ChatWelcomeMessageNickname]: 'System',
    [LocalizationKey.ChatMessagePlaceholder]: 'Write to chat',
    [LocalizationKey.SearchByName]: 'Search by name',
    [LocalizationKey.RootCategories]: 'Root categories',
    [LocalizationKey.Category]: 'Category',
    [LocalizationKey.Subcategory]: 'Subcategory',
    [LocalizationKey.SelectCategorySubcategory]:
      'To search and add a question, specify a category and subcategory, and then select questions from the list',
    [LocalizationKey.CallRecording]: 'The meeting is being recorded',
    [LocalizationKey.Archive]: 'Archive',
    [LocalizationKey.ArchiveLoading]: 'Archiving...',
    [LocalizationKey.Unarchive]: 'Unarchive',
    [LocalizationKey.UnarchiveLoading]: 'Unarchiving...',
    [LocalizationKey.NoQuestionsSelector]: 'No questions available',
    [LocalizationKey.Join]: 'Join',
    [LocalizationKey.JoiningRoom]: 'Ready to join?',
    [LocalizationKey.SetupDevices]: 'Set up camera and microphone',
    [LocalizationKey.Settings]: 'Settings',
    [LocalizationKey.Chat]: 'Chat',
    [LocalizationKey.Exit]: 'Leave',
    [LocalizationKey.Theme]: 'Theme',
    [LocalizationKey.ThemeSystem]: 'System',
    [LocalizationKey.ThemeLight]: 'Light theme',
    [LocalizationKey.ThemeDark]: 'Dark theme',
    [LocalizationKey.Language]: 'Language',
    [LocalizationKey.PleaseSelectRecognitionLanguage]:
      'Please indicate the language you will speak',
    [LocalizationKey.RecognitionLanguage]: 'Transcription language',
    [LocalizationKey.You]: 'You',
    [LocalizationKey.NoRecords]: 'List is empty',
    [LocalizationKey.ConnectionError]: 'Connection error',
    [LocalizationKey.RoomConnectionError]:
      'Connection to the room has been lost',
    [LocalizationKey.LocalizationLangEn]: 'English',
    [LocalizationKey.LocalizationLangRu]: 'Русский',
    [LocalizationKey.AiAssistantName]: 'Michael (Alpha)',
    [LocalizationKey.ErrorApplyRoomInvite]: 'Meeting invitation is invalid',
    [LocalizationKey.RoomInvitesLoading]: 'Loading room invites',
    [LocalizationKey.Invitations]: 'Invitations',
    [LocalizationKey.InviteViaLink]: 'Invite via link',
    [LocalizationKey.RefreshAll]: 'Refresh all',
    [LocalizationKey.NextRoomQuestion]: 'Next question',
    [LocalizationKey.CopiedToClipboard]: 'Copied to clipboard',
    [LocalizationKey.Of]: 'of',
    [LocalizationKey.RoomQuestionEvaluationTitle]: 'Rate the answer',
    [LocalizationKey.SaveRoomQuestionEvaluationWarningLine1]:
      'Are you sure you want to save review?',
    [LocalizationKey.SaveRoomQuestionEvaluationWarningLine2]:
      'After saving, editing will not be possible.',
    [LocalizationKey.CloseRoomWithoutQuestionEvaluationWarningLine1]:
      "Are you sure you want to close review without waiting for other participants' reviews?",
    [LocalizationKey.CloseRoomWithoutQuestionEvaluationWarningLine2]:
      'If other participants leave review, review will end automatically.',
    [LocalizationKey.MarksGroupBad]: 'Bad',
    [LocalizationKey.MarksGroupMedium]: 'Med.',
    [LocalizationKey.MarksGroupGood]: 'Good',
    [LocalizationKey.MarksGroupPerfect]: 'Perfect',
    [LocalizationKey.NotFound]: 'Not found',
    [LocalizationKey.AverageCandidateMark]: 'Average candidate score',
    [LocalizationKey.MarksForQuestions]: 'Points for questions',
    [LocalizationKey.OpinionsAndMarks]: 'Opinions and ratings',
    [LocalizationKey.QuestionAnswerDetails]: 'Question answer details',
    [LocalizationKey.EmptyRoomNameError]: 'Please provide the meeting name',
    [LocalizationKey.EmptyRoomQuestionTreeError]:
      'Please provide the question tree',
    [LocalizationKey.RoomEmptyStartTimeError]:
      'Please enter meeting start time',
    [LocalizationKey.RoomStartTimeMustBeGreaterError]:
      'Meeting start time must be greater than the current time',
    [LocalizationKey.RoomEmptyQuestionsListError]:
      'Please add questions to the list of questions',
    [LocalizationKey.InterviewHistoryTitle]: 'Interview history',
    [LocalizationKey.RoomReviewSave]: 'Finish review',
    [LocalizationKey.RoomReviewWaiting]: 'Waiting for evaluation',
    [LocalizationKey.EmptyCommentQuestionEvaluation]:
      'Write a comment to answer the question',
    [LocalizationKey.QurstionTranscription]: 'Transcription of the answer',
    [LocalizationKey.QuestionCode]: 'Question code',
    [LocalizationKey.AnswerCode]: 'Answer code',
    [LocalizationKey.WeAwareOfProblem]:
      'We are already aware of the problem and are working on a solution',
    [LocalizationKey.CurrentQuestionNotBeSaved]:
      'Current question will not be saved',
    [LocalizationKey.CurrentRoomNotBeSaved]: 'Current room will not be saved',
    [LocalizationKey.LoadingAccountError]: 'Failed to load user profile',
    [LocalizationKey.LoadingAccountErrorTitle]: 'Account loading error',
    [LocalizationKey.Opinions]: 'Opinions',
    [LocalizationKey.Transcription]: 'Transcription',
    [LocalizationKey.CompleteAndEvaluateCandidate]:
      'Complete and evaluate candidate',
    [LocalizationKey.CategoriesArchive]: 'Categories archive',
    [LocalizationKey.QuestionsArchive]: 'Questions archive',
    [LocalizationKey.WaitingInterviewStart]: 'Waiting to start the interview',
    [LocalizationKey.RoomStartDescription]:
      'Once the interview begins, the first question from the prepared list will be asked',
    [LocalizationKey.NoData]: 'No data',
    [LocalizationKey.UserConnectedToRoom]: 'connected',
    [LocalizationKey.NotEnoughRights]: 'Insufficient rights to view content',
    [LocalizationKey.WebcamBackgroundBlur]: 'Background blur',
    [LocalizationKey.Feedback]: 'Feedback',
    [LocalizationKey.RateMeDescription]:
      'At the end of your answer, say "{RateMeCommand}" and assistant will rate you.',
    [LocalizationKey.RateMeCommands]: 'rate me',
    [LocalizationKey.LetsBeginDescription]:
      'To start an interview, say "{LetsStartCommand}".',
    [LocalizationKey.LetsBeginCommand]: "let's begin",
    [LocalizationKey.HomeDescription]: 'Preparing for interviews.',
    [LocalizationKey.QuestionTreesPageName]: 'Question trees',
    [LocalizationKey.CreateQuestionTree]: 'Create question trees',
    [LocalizationKey.QuestionTree]: 'Question tree',
    [LocalizationKey.QuestionTreeName]: 'Question tree name',
    [LocalizationKey.QuestionTreeNodeDelete]: 'Delete',
    [LocalizationKey.QuestionTreeNodeNewItemBelow]: 'New item below',
    [LocalizationKey.QuestionTreeNodeNewItemInside]: 'New item inside',
    [LocalizationKey.QuestionTreeNodeMoveUp]: 'Move up',
    [LocalizationKey.QuestionTreeNodeMoveDown]: 'Move down',
    [LocalizationKey.QuestionTreeNodeMoveLeft]: 'Move out',
    [LocalizationKey.QuestionTreeNodeMoveRight]: 'Move in',
    [LocalizationKey.QuestionTreeCreatedSuccessfully]:
      'Question tree created successfully',
    [LocalizationKey.QuestionTreeUpdatedSuccessfully]:
      'Question tree updated successfully',
    [LocalizationKey.QuestionTreeExpandAll]: 'Expand all',
    [LocalizationKey.QuestionTreeCollapseAll]: 'Collapse all',
    [LocalizationKey.QuestionTreeRootNode]: 'Beginning',
    [LocalizationKey.From10]: 'from 10',
    [LocalizationKey.AnswerEvaluation]: 'Evaluation of the answer',
    [LocalizationKey.ExampleOfCorrectAnswer]: 'Correct answer',
    [LocalizationKey.Test]: 'Test',
    [LocalizationKey.Run]: 'Run',
    [LocalizationKey.ExpectsExecuteResults]: 'Result of code execution',
    [LocalizationKey.ExpectsExecuteInput]: 'Input',
    [LocalizationKey.ExpectsExecuteOutput]: 'Result',
    [LocalizationKey.ExpectsExecuteOutputExpected]: 'Expected result',
    [LocalizationKey.ExpectsExecuteResultsPassed]: 'Checks passed successfully',
    [LocalizationKey.ExpectsExecuteResultsNotPassed]: 'Check failed',
    [LocalizationKey.ExecutionResultsSubmit]: 'Rate the answer',
    [LocalizationKey.Completed]: 'Completed',
    [LocalizationKey.MeetingBeingRecorded]: 'Meeting is being recorded',
    [LocalizationKey.NewNotifications]: 'New notifications',
    [LocalizationKey.NoNewNotifications]: 'No new notifications',
    [LocalizationKey.Clear]: 'Clear',
    [LocalizationKey.AnswerAgain]: 'Answer again',
    [LocalizationKey.RoadmapsPageName]: 'Direction',
    [LocalizationKey.RoadmapsPageDescription]:
      'In what direction do you need to improve?',
    [LocalizationKey.RoadmapsArchivePageName]: 'Direction Archive',
    [LocalizationKey.RoadmapCreatePageName]: 'Create Roadmap',
    [LocalizationKey.RoadmapYourProgress]: 'Your Progress',
    [LocalizationKey.RoadmapLevel0]: 'Impostor',
    [LocalizationKey.RoadmapLevel1]: 'Newbie',
    [LocalizationKey.RoadmapLevel2]: 'Experienced',
    [LocalizationKey.RoadmapLevel3]: 'Interview Master',
    [LocalizationKey.RoadmapToFinish]: 'to finish',
    [LocalizationKey.HomeInfoTitle]: 'Interviews with AI',
    [LocalizationKey.HomeInfoTheoryBlockTitle]: 'Theory interviews',
    [LocalizationKey.HomeInfoTheoryBlockInfo]:
      'Move beyond static information. Interact, debate, and refine your understanding through conversation.',
    [LocalizationKey.HomeInfoCodingBlockTitle]: 'Coding Interviews',
    [LocalizationKey.HomeInfoCodingBlockInfo]:
      "Whether you're practicing algorithms, data structures, or system design problems, our AI analyzes your solutions just like a real interviewer—spotting errors, suggesting optimizations, and helping you improve faster.",
    [LocalizationKey.HomeInfoPricingTitle]: 'Pricing',
    [LocalizationKey.HomeInfoPricingFree]: 'Free',
    [LocalizationKey.HomeInfoPricingPoint1]: 'Full access to all questions',
    [LocalizationKey.HomeInfoPricingPoint2]: 'Endless number of interviews',
    [LocalizationKey.StartAnswer]: 'Start answer',
    [LocalizationKey.Learn]: 'Learn',
    [LocalizationKey.ErrorRecognitionNotSupportedTitle]:
      'Your browser does not support speech recognition.',
    [LocalizationKey.ErrorRecognitionNotSupportedDescription]:
      'Please try updating your browser or using a modern version of Chrome, Edge or Safari. We apologize for the inconvenience.',
    [LocalizationKey.BusinessAnalyticPageName]: 'Analytics',
    [LocalizationKey.AllowAccessToMicrophone]:
      'Please allow access to microphone',
    [LocalizationKey.AllowAccessToMicrophoneDescription]:
      'You have not allowed access to microphone in your browser settings.',
    [LocalizationKey.TextAnswer]: 'Text response',
    [LocalizationKey.SendAnswer]: 'Send answer',
    [LocalizationKey.StartInterview]: 'Start interview',
    [LocalizationKey.Preview]: 'Preview',
    [LocalizationKey.SkipQuestion]: 'Skip question',
  },
  [LocalizationLang.ru]: {
    [LocalizationKey.HighlightsRoomsPageName]: 'Комнаты',
    [LocalizationKey.CurrentRoomsPageName]: 'Актуальные комнаты',
    [LocalizationKey.ClosedRoomsPageName]: 'Завершенные комнаты',
    [LocalizationKey.QuestionsPageName]: 'Вопросы',
    [LocalizationKey.CategoriesPageName]: 'Категории',
    [LocalizationKey.RoomReviewPageName]: 'Результаты собеседования',
    [LocalizationKey.CandidateOpinion]: 'Ваше мнение о кандидате',
    [LocalizationKey.CandidateMarks]:
      'Ваши оценки кандидата и комментарии к вопросам',
    [LocalizationKey.DoNotRate]: 'Не оценивать',
    [LocalizationKey.Page]: 'Страница',
    [LocalizationKey.LogOut]: 'Выйти',
    [LocalizationKey.Edit]: 'Редактировать',
    [LocalizationKey.Viewer]: 'Зритель',
    [LocalizationKey.Expert]: 'Собеседующий',
    [LocalizationKey.Examinee]: 'Собеседуемый',
    [LocalizationKey.Save]: 'Сохранить',
    [LocalizationKey.Saved]: 'Сохранено',
    [LocalizationKey.CreateQuestion]: 'Создание вопроса',
    [LocalizationKey.EditQuestion]: 'Редактирование вопроса',
    [LocalizationKey.QuestionText]: 'Текст вопроса',
    [LocalizationKey.QuestionType]: 'Тип вопроса',
    [LocalizationKey.QuestionTypePrivate]: 'Личный',
    [LocalizationKey.QuestionCodeEditor]: 'Код к вопросу',
    [LocalizationKey.QuestionAddCodeEditor]: 'Добавить код вопроса',
    [LocalizationKey.QuestionRemoveCodeEditor]: 'Удалить код',
    [LocalizationKey.QuestionAnswerOptionDefaultName]: 'Ответ',
    [LocalizationKey.QuestionAnswerOptions]: 'Варианты ответа',
    [LocalizationKey.QuestionAddAnswerOption]: 'Добавить вариант ответа',
    [LocalizationKey.QuestionDeleteAnswerOption]: 'Удалить вариант ответа',
    [LocalizationKey.QuestionAnswerOptionName]: 'Название варианта ответа',
    [LocalizationKey.QuestionTypePublic]: 'Публичный',
    [LocalizationKey.CreateCategory]: 'Создать категорию',
    [LocalizationKey.CategoryName]: 'Имя категории',
    [LocalizationKey.CategoryParent]: 'Родительская категория',
    [LocalizationKey.CategoryOrder]: 'Позиция в списке',
    [LocalizationKey.Create]: 'Создать',
    [LocalizationKey.Continue]: 'Дальше',
    [LocalizationKey.Cancel]: 'Отменить',
    [LocalizationKey.Close]: 'Закрыть',
    [LocalizationKey.CloselWithoutSave]: 'Выйти без сохранения',
    [LocalizationKey.Stay]: 'Остаться',
    [LocalizationKey.Error]: 'Ошибка',
    [LocalizationKey.Loading]: 'Загрузка',
    [LocalizationKey.NotSelected]: 'Не выбрано',
    [LocalizationKey.QuestionCreatedSuccessfully]: 'Вопрос успешно создан',
    [LocalizationKey.QuestionUpdatedSuccessfully]: 'Вопрос успешно обновлён',
    [LocalizationKey.CategoryCreatedSuccessfully]: 'Категория успешно создана',
    [LocalizationKey.CategoryUpdatedSuccessfully]:
      'Категория успешно обновлёна',
    [LocalizationKey.LoadingRoom]: 'Загрузка встречи',
    [LocalizationKey.ErrorLoadingRoom]: 'Ошибка загрузки встречи',
    [LocalizationKey.ErrorLoadingRoomState]:
      'Ошибка загрузки состояния встречи',
    [LocalizationKey.ErrorSendingActiveQuestion]: 'Ошибка в установке вопроса',
    [LocalizationKey.ReactionsLoadingError]: 'Ошибка загрузки реакций',
    [LocalizationKey.ErrorSendingReaction]: 'Ошибка в отправке реакции',
    [LocalizationKey.TermsOfUsageAcceptance]:
      'Входя, вы подтверждаете, что прочитали,\nпоняли и соглашаетесь с ',
    [LocalizationKey.TermsOfUsage]: 'Условиями использования',
    [LocalizationKey.Login]: 'Войти',
    [LocalizationKey.CloseRoom]: 'Закрыть встречу',
    [LocalizationKey.CloseRoomWithoutReview]:
      'Закрыть встречу не дожидаясь оценок',
    [LocalizationKey.StartRoom]: 'Начать собеседование',
    [LocalizationKey.StartReviewRoom]: 'Начать разбор встречи',
    [LocalizationKey.StartReviewRoomModalTitle]:
      'Начать заполнение отчёта по встрече?',
    [LocalizationKey.Yes]: 'Да ✔️',
    [LocalizationKey.No]: 'Нет ❌',
    [LocalizationKey.RoomStatusNew]: 'Ожидание начала',
    [LocalizationKey.RoomStatusActive]: 'Идёт встреча',
    [LocalizationKey.RoomStatusReview]: 'Разбор',
    [LocalizationKey.RoomStatusClose]: 'Закрыта',
    [LocalizationKey.RoomStatusExpire]: 'Истекла',
    [LocalizationKey.TagsLoading]: 'Загрузка тэгов',
    [LocalizationKey.NoTags]: 'Тэги отсутствуют',
    [LocalizationKey.BuildHash]: 'Сборка',
    [LocalizationKey.CreateRoom]: 'Создать встречу',
    [LocalizationKey.NewRoom]: 'Новая комната',
    [LocalizationKey.EditRoom]: 'Редактирование комнаты',
    [LocalizationKey.CreateRoomStep1]: 'Шаг 1 - Наполнение комнаты',
    [LocalizationKey.CreateRoomStep2]: 'Шаг 2 - Приглашение участников',
    [LocalizationKey.RoomName]: 'Имя встречи',
    [LocalizationKey.RoomNamePrompt]:
      'В названии укажите имя кандидата и должность, на которую пройдет собеседование',
    [LocalizationKey.RoomDateAndTime]: 'Дата и время',
    [LocalizationKey.RoomQuestions]: 'Список вопросов',
    [LocalizationKey.RoomSelectedQuestions]: 'Выбрано вопросов',
    [LocalizationKey.RoomDuration]: 'Длительность',
    [LocalizationKey.AddRoomQuestions]: 'Добавить вопросы',
    [LocalizationKey.RoomParticipants]: 'Участники',
    [LocalizationKey.SearchByValue]: 'Поиск по содержимому',
    [LocalizationKey.UserStreamError]:
      'Не удалось получить доступ к камере и микрофону',
    [LocalizationKey.ChatWelcomeMessage]: 'Добро пожаловать',
    [LocalizationKey.ChatWelcomeMessageNickname]: 'Система',
    [LocalizationKey.ChatMessagePlaceholder]: 'Написать в чат',
    [LocalizationKey.SearchByName]: 'Поиск по имени',
    [LocalizationKey.RootCategories]: 'Корневые категории',
    [LocalizationKey.Category]: 'Категория',
    [LocalizationKey.Subcategory]: 'Подкатегория',
    [LocalizationKey.SelectCategorySubcategory]:
      'Для поиска и добавления вопроса укажите категорию и подкатегорию, а затем выберите вопросы из списка',
    [LocalizationKey.CallRecording]: 'Встреча записывается',
    [LocalizationKey.Archive]: 'В архив',
    [LocalizationKey.ArchiveLoading]: 'Ахивирование...',
    [LocalizationKey.Unarchive]: 'Разархивировать',
    [LocalizationKey.UnarchiveLoading]: 'Разахивирование...',
    [LocalizationKey.NoQuestionsSelector]: 'Нет доступных вопросов',
    [LocalizationKey.Join]: 'Присоединиться',
    [LocalizationKey.JoiningRoom]: 'Готовы присоединиться?',
    [LocalizationKey.SetupDevices]: 'Настроить камеру и микрофон',
    [LocalizationKey.Settings]: 'Настройки',
    [LocalizationKey.Chat]: 'Чат',
    [LocalizationKey.Exit]: 'Выйти',
    [LocalizationKey.Theme]: 'Тема оформления',
    [LocalizationKey.ThemeSystem]: 'Системная',
    [LocalizationKey.ThemeLight]: 'Светлая тема',
    [LocalizationKey.ThemeDark]: 'Тёмная тема',
    [LocalizationKey.Language]: 'Язык',
    [LocalizationKey.PleaseSelectRecognitionLanguage]:
      'Пожалуйста, укажите язык на котором будете говорить',
    [LocalizationKey.RecognitionLanguage]: 'Язык транскрибации',
    [LocalizationKey.You]: 'Вы',
    [LocalizationKey.NoRecords]: 'Список пуст',
    [LocalizationKey.ConnectionError]: 'Ошибка подключения',
    [LocalizationKey.RoomConnectionError]: 'Соединение с комнатой потеряно',
    [LocalizationKey.LocalizationLangEn]: 'English',
    [LocalizationKey.LocalizationLangRu]: 'Русский',
    [LocalizationKey.AiAssistantName]: 'Михаил (Альфа)',
    [LocalizationKey.ErrorApplyRoomInvite]:
      'Приглашение на встречу недействительно',
    [LocalizationKey.RoomInvitesLoading]: 'Загрузка приглашений в комнату',
    [LocalizationKey.Invitations]: 'Приглашения',
    [LocalizationKey.InviteViaLink]: 'Пригласить по ссылке',
    [LocalizationKey.RefreshAll]: 'Обновить все',
    [LocalizationKey.NextRoomQuestion]: 'Следующий вопрос',
    [LocalizationKey.CopiedToClipboard]: 'Скопировано в буфер обмена',
    [LocalizationKey.Of]: 'из',
    [LocalizationKey.RoomQuestionEvaluationTitle]: 'Оцените ответ',
    [LocalizationKey.SaveRoomQuestionEvaluationWarningLine1]:
      'Вы действительно хотите сохранить отзыв?',
    [LocalizationKey.SaveRoomQuestionEvaluationWarningLine2]:
      'После сохранения редактирование будет невозможным.',
    [LocalizationKey.CloseRoomWithoutQuestionEvaluationWarningLine1]:
      'Вы действительно хотите закрыть оценивание не дожидаясь оценок других участников?',
    [LocalizationKey.CloseRoomWithoutQuestionEvaluationWarningLine2]:
      'Если остальные участники оставят отзывы, оценивание завершится автоматически.',
    [LocalizationKey.MarksGroupBad]: 'Плохо',
    [LocalizationKey.MarksGroupMedium]: 'Удовлетв.',
    [LocalizationKey.MarksGroupGood]: 'Хорошо',
    [LocalizationKey.MarksGroupPerfect]: 'Отлично',
    [LocalizationKey.NotFound]: 'Не найдено',
    [LocalizationKey.AverageCandidateMark]: 'Средний балл кандидата',
    [LocalizationKey.MarksForQuestions]: 'Баллы за вопросы',
    [LocalizationKey.OpinionsAndMarks]: 'Мнения и оценки',
    [LocalizationKey.QuestionAnswerDetails]: 'Детали ответа на вопрос',
    [LocalizationKey.EmptyRoomNameError]: 'Пожалуйста, укажите имя встречи',
    [LocalizationKey.EmptyRoomQuestionTreeError]:
      'Пожалуйста, укажите дерево вопросов',
    [LocalizationKey.RoomEmptyStartTimeError]:
      'Пожалуйста, укажите время начала встречи',
    [LocalizationKey.RoomStartTimeMustBeGreaterError]:
      'Время начала встречи должно быть больше текущего времени',
    [LocalizationKey.RoomEmptyQuestionsListError]:
      'Пожалуйста, добавьте вопросы в список вопросов',
    [LocalizationKey.InterviewHistoryTitle]: 'История собеседований',
    [LocalizationKey.RoomReviewSave]: 'Завершить заполнение',
    [LocalizationKey.RoomReviewWaiting]: 'Ожидание оценки',
    [LocalizationKey.EmptyCommentQuestionEvaluation]:
      'Напишите комментарий  к ответу на вопрос',
    [LocalizationKey.QurstionTranscription]: 'Транскрибация ответа',
    [LocalizationKey.QuestionCode]: 'Код вопроса',
    [LocalizationKey.AnswerCode]: 'Код ответа',
    [LocalizationKey.WeAwareOfProblem]:
      'Мы уже знаем о проблеме и работаем над ее решением',
    [LocalizationKey.CurrentQuestionNotBeSaved]:
      'Текущий вопрос не будет сохранен',
    [LocalizationKey.CurrentRoomNotBeSaved]:
      'Текущая комната не будет сохранена',
    [LocalizationKey.LoadingAccountError]:
      'Не удалось загрузить профиль пользователя',
    [LocalizationKey.LoadingAccountErrorTitle]: 'Ошибка загрузки профиля',
    [LocalizationKey.Opinions]: 'Мнения',
    [LocalizationKey.Transcription]: 'Транскрибация',
    [LocalizationKey.CompleteAndEvaluateCandidate]:
      'Завершить и оценить кандидата',
    [LocalizationKey.CategoriesArchive]: 'Архив категорий',
    [LocalizationKey.QuestionsArchive]: 'Архив вопросов',
    [LocalizationKey.WaitingInterviewStart]: 'Ожидание начала собеседования',
    [LocalizationKey.RoomStartDescription]:
      'После начала собеседования будет установлен первый вопрос из подготовленного списка',
    [LocalizationKey.NoData]: 'Нет данных',
    [LocalizationKey.UserConnectedToRoom]: 'подключился(ась)',
    [LocalizationKey.NotEnoughRights]:
      'Недостаточно прав для просмотра содержимого',
    [LocalizationKey.WebcamBackgroundBlur]: 'Размытие фона',
    [LocalizationKey.Feedback]: 'Обратная связь',
    [LocalizationKey.RateMeDescription]:
      'В конце ответа скажите "{RateMeCommand}" и ассистент оценит вас.',
    [LocalizationKey.RateMeCommands]: 'оцени меня|цени меня',
    [LocalizationKey.LetsBeginDescription]:
      'Для начала собеседования скажите "{LetsStartCommand}".',
    [LocalizationKey.LetsBeginCommand]: 'давай начнём',
    [LocalizationKey.HomeDescription]: 'Подготовка к собеседованиям.',
    [LocalizationKey.QuestionTreesPageName]: 'Деревья вопросов',
    [LocalizationKey.CreateQuestionTree]: 'Создать дерево вопросов',
    [LocalizationKey.QuestionTree]: 'Дерево вопросов',
    [LocalizationKey.QuestionTreeName]: 'Имя дерева вопросов',
    [LocalizationKey.QuestionTreeNodeDelete]: 'Удалить',
    [LocalizationKey.QuestionTreeNodeNewItemBelow]: 'Новый элемент рядом',
    [LocalizationKey.QuestionTreeNodeNewItemInside]: 'Новый элемент внутри',
    [LocalizationKey.QuestionTreeNodeMoveUp]: 'Переместить вверх',
    [LocalizationKey.QuestionTreeNodeMoveDown]: 'Переместить вниз',
    [LocalizationKey.QuestionTreeNodeMoveLeft]: 'Переместить наружу',
    [LocalizationKey.QuestionTreeNodeMoveRight]: 'Переместить внутрь',
    [LocalizationKey.QuestionTreeCreatedSuccessfully]:
      'Дерево вопросов создано успешно',
    [LocalizationKey.QuestionTreeUpdatedSuccessfully]:
      'Дерево вопросов успешно обновлено',
    [LocalizationKey.QuestionTreeExpandAll]: 'Развернуть все',
    [LocalizationKey.QuestionTreeCollapseAll]: 'Свернуть все',
    [LocalizationKey.QuestionTreeRootNode]: 'Начало',
    [LocalizationKey.From10]: 'из 10',
    [LocalizationKey.AnswerEvaluation]: 'Оценка ответа',
    [LocalizationKey.ExampleOfCorrectAnswer]: 'Правильный ответ',
    [LocalizationKey.Test]: 'Тест',
    [LocalizationKey.Run]: 'Запустить',
    [LocalizationKey.ExpectsExecuteResults]: 'Результат запуска кода',
    [LocalizationKey.ExpectsExecuteInput]: 'Входные данные',
    [LocalizationKey.ExpectsExecuteOutput]: 'Полученный результат',
    [LocalizationKey.ExpectsExecuteOutputExpected]: 'Ожидаемый результат',
    [LocalizationKey.ExpectsExecuteResultsPassed]: 'Проверки успешно пройдены',
    [LocalizationKey.ExpectsExecuteResultsNotPassed]: 'Проверка не пройдена',
    [LocalizationKey.ExecutionResultsSubmit]: 'Оценить ответ',
    [LocalizationKey.Completed]: 'Пройдено',
    [LocalizationKey.MeetingBeingRecorded]: 'Идет запись встречи',
    [LocalizationKey.NewNotifications]: 'Новые уведомления',
    [LocalizationKey.NoNewNotifications]: 'Новых уведомлений нет',
    [LocalizationKey.Clear]: 'Очистить',
    [LocalizationKey.AnswerAgain]: 'Ответить заново',
    [LocalizationKey.RoadmapsPageName]: 'Направления',
    [LocalizationKey.RoadmapsPageDescription]:
      'Какое направление вам нужно прокачать?',
    [LocalizationKey.RoadmapsArchivePageName]: 'Архив направлений',
    [LocalizationKey.RoadmapCreatePageName]: 'Создать Roadmap',
    [LocalizationKey.RoadmapYourProgress]: 'Ваш прогресс',
    [LocalizationKey.RoadmapLevel0]: 'Самозванец(ка)',
    [LocalizationKey.RoadmapLevel1]: 'Новичок',
    [LocalizationKey.RoadmapLevel2]: 'Опытный',
    [LocalizationKey.RoadmapLevel3]: 'Мастер собеседований',
    [LocalizationKey.RoadmapToFinish]: 'до завершения',
    [LocalizationKey.HomeInfoTitle]: 'Собеседования с AI',
    [LocalizationKey.HomeInfoTheoryBlockTitle]: 'Собеседования по теории',
    [LocalizationKey.HomeInfoTheoryBlockInfo]:
      'Выходите за рамки статической информации. Взаимодействуйте, дискутируйте и совершенствуйте свое понимание посредством разговора.',
    [LocalizationKey.HomeInfoCodingBlockTitle]: 'Собеседования по кодингу',
    [LocalizationKey.HomeInfoCodingBlockInfo]:
      'Независимо от того, практикуете ли вы алгоритмы, структуры данных или проблемы проектирования систем, наш ИИ анализирует ваши решения так же, как настоящий интервьюер, выявляя ошибки, предлагая оптимизации и помогая вам быстрее совершенствоваться.',
    [LocalizationKey.HomeInfoPricingTitle]: 'Стоимость',
    [LocalizationKey.HomeInfoPricingFree]: 'Бесплатно',
    [LocalizationKey.HomeInfoPricingPoint1]: 'Полный доступ к базе вопросов',
    [LocalizationKey.HomeInfoPricingPoint2]:
      'Бесконечное количество собеседований',
    [LocalizationKey.StartAnswer]: 'Начать ответ',
    [LocalizationKey.Learn]: 'Изучение',
    [LocalizationKey.ErrorRecognitionNotSupportedTitle]:
      'Ваш браузер не поддерживает функцию распознавания речи.',
    [LocalizationKey.ErrorRecognitionNotSupportedDescription]:
      ' Попробуйте обновить браузер или использовать современные версии Chrome, Edge или Safari. Приносим извинения за неудобства.',
    [LocalizationKey.BusinessAnalyticPageName]: 'Аналитика',
    [LocalizationKey.AllowAccessToMicrophone]:
      'Пожалуйста, разрешите доступ к микрофону',
    [LocalizationKey.AllowAccessToMicrophoneDescription]:
      'Вы не разрешили доступ к микрофону в настройках браузера.',
    [LocalizationKey.TextAnswer]: 'Текстовый ответ',
    [LocalizationKey.SendAnswer]: 'Отправить ответ',
    [LocalizationKey.StartInterview]: 'Начать собеседование',
    [LocalizationKey.Preview]: 'Предпросмотр',
    [LocalizationKey.SkipQuestion]: 'Пропустить вопрос',
  },
};
