import { LocalizationLang } from './context/LocalizationContext';

export const enum LocalizationKey {
  SpeechRecognitionLang,
  AppName,
  AppDescription,
  WelcomeMessage,
  CurrentRoomsPageName,
  ClosedRoomsPageName,
  RoomsPageName,
  QuestionsPageName,
  CategoriesPageName,
  UnauthorizedMessage,
  Page,
  LogOut,
  Edit,
  Viewer,
  Viewers,
  Expert,
  Examinee,
  Save,
  CreateQuestion,
  QuestionText,
  QuestionType,
  QuestionTypePublic,
  QuestionTypePrivate,
  QuestionCodeEditor,
  QuestionAddCodeEditor,
  QuestionRemoveCodeEditor,
  QuestionAnswerOptions,
  QuestionAddAnswerOption,
  QuestionDeleteAnswerOption,
  QuestionAnswerOptionName,
  CreateCategory,
  CategoryName,
  CategoryParent,
  Create,
  Continue,
  Cancel,
  Error,
  NotSelected,
  QuestionCreatedSuccessfully,
  QuestionUpdatedSuccessfully,
  ShowClosedQuestions,
  SelectActiveQuestion,
  SendingActiveQuestion,
  CreatingRoomQuestion,
  CategoryCreatedSuccessfully,
  CategoryUpdatedSuccessfully,
  LoadingRoom,
  ErrorLoadingRoom,
  LoadingRoomState,
  ErrorLoadingRoomState,
  RoomCreated,
  ErrorSendingActiveQuestion,
  ErrorCreatingRoomQuestion,
  ReactionsLoadingError,
  ErrorSendingReaction,
  GetRoomEvent,
  ErrorGetRoomEvent,
  ErrorSendingRoomEvent,
  TermsOfUsage,
  Login,
  LikeTable,
  DislikeTable,
  Like,
  Dislike,
  CodeEditor,
  Question,
  ActiveQuestion,
  QuestionsSummary,
  FailedToCalculateMark,
  RoomAnayticsSummary,
  MarkNotCalculated,
  MarkWithPlus,
  MarkWithMinus,
  MarkAveragePrefix,
  MarkAverage,
  MarkPostfixCool,
  MarkPostfixAverage,
  MarkPostfixBad,
  MarkSmmary,
  CloseRoom,
  WaitingRoom,
  StartReviewRoom,
  CloseRoomModalTitle,
  StartReviewRoomModalTitle,
  CloseRoomLoading,
  Yes,
  No,
  RoomStatusNew,
  RoomStatusActive,
  RoomStatusReview,
  RoomStatusClose,
  Reviews,
  AddReview,
  AddReviewPlaceholder,
  Send,
  WithLove,
  TagsPlaceholder,
  TagsLoading,
  NoTags,
  SearchByTags,
  BuildHash,
  CreateRoom,
  NewRoom,
  AddingRoomQuestions,
  CreatingRoom,
  CreateRoomStep1,
  CreateRoomStep2,
  RoomName,
  RoomNamePrompt,
  RoomDateAndTime,
  RoomQuestions,
  RoomSelectedQuestions,
  AddRoomQuestions,
  RoomParticipants,
  RoomExperts,
  RoomExaminees,
  SearchByValue,
  Recognized,
  UserStreamError,
  ChatWelcomeMessage,
  ChatWelcomeMessageNickname,
  ChatMessagePlaceholder,
  SendToChat,
  SearchByName,
  ParticipatingRooms,
  RootCategories,
  Category,
  SelectCategorySubcategory,
  ClosedRooms,
  ToRooms,
  Warning,
  CallRecording,
  VoiceRecognitionNotSupported,
  VoiceRecognition,
  Archive,
  ArchiveLoading,
  NoQuestionsSelector,
  Join,
  JoiningRoom,
  JoinAs,
  SetupDevices,
  Camera,
  Microphone,
  Settings,
  Chat,
  ScreenShare,
  Exit,
  ChatTab,
  RecognitionTab,
  Theme,
  ThemeSystem,
  ThemeLight,
  ThemeDark,
  Language,
  FontSize,
  You,
  NoRecords,
  ConnectionError,
  RoomConnectionError,
  LocalizationLangEn,
  LocalizationLangRu,
  AiAssistantName,
  AiAssistantWelcomePrompt,
  ErrorApplyRoomInvite,
  RoomInvitesLoading,
  Invitations,
  InviteViaLink,
  RefreshAll,
  NextRoomQuestion,
  CopiedToClipboard,
};

export const LocalizationCaptions: Record<LocalizationLang, Record<LocalizationKey, string>> = {
  [LocalizationLang.en]: {
    [LocalizationKey.SpeechRecognitionLang]: 'en',
    [LocalizationKey.AppName]: 'Interview Platform',
    [LocalizationKey.AppDescription]: 'Interactive interview platform with the ability to generate detailed reports.',
    [LocalizationKey.WelcomeMessage]: 'Welcome',
    [LocalizationKey.CurrentRoomsPageName]: 'Current rooms',
    [LocalizationKey.ClosedRoomsPageName]: 'Closed rooms',
    [LocalizationKey.RoomsPageName]: 'Meetings',
    [LocalizationKey.QuestionsPageName]: 'Questions',
    [LocalizationKey.CategoriesPageName]: 'Categories',
    [LocalizationKey.UnauthorizedMessage]: 'Unauthorized',
    [LocalizationKey.Page]: 'Page',
    [LocalizationKey.LogOut]: 'Logout',
    [LocalizationKey.Edit]: 'Edit',
    [LocalizationKey.Viewer]: 'Viewer',
    [LocalizationKey.Viewers]: 'Viewerss',
    [LocalizationKey.Expert]: 'Expert',
    [LocalizationKey.Examinee]: 'Examinee',
    [LocalizationKey.Save]: 'Save',
    [LocalizationKey.CreateQuestion]: 'Create question',
    [LocalizationKey.QuestionText]: 'Text',
    [LocalizationKey.QuestionType]: 'Type',
    [LocalizationKey.QuestionTypePrivate]: 'Private',
    [LocalizationKey.QuestionCodeEditor]: 'Question code',
    [LocalizationKey.QuestionAddCodeEditor]: 'Add question code',
    [LocalizationKey.QuestionRemoveCodeEditor]: 'Remove code',
    [LocalizationKey.QuestionAnswerOptions]: 'Answer options',
    [LocalizationKey.QuestionAddAnswerOption]: 'Add answer option',
    [LocalizationKey.QuestionDeleteAnswerOption]: 'Delete answer option',
    [LocalizationKey.QuestionAnswerOptionName]: 'Answer option name',
    [LocalizationKey.QuestionTypePublic]: 'Public',
    [LocalizationKey.CreateCategory]: 'Create category',
    [LocalizationKey.CategoryName]: 'Category name',
    [LocalizationKey.CategoryParent]: 'Category parent',
    [LocalizationKey.Create]: 'Create',
    [LocalizationKey.Continue]: 'Continue',
    [LocalizationKey.Cancel]: 'Cancel',
    [LocalizationKey.Error]: 'Error',
    [LocalizationKey.NotSelected]: 'Not selected',
    [LocalizationKey.QuestionCreatedSuccessfully]: 'Question created successfully',
    [LocalizationKey.QuestionUpdatedSuccessfully]: 'Question updated successfully',
    [LocalizationKey.ShowClosedQuestions]: 'Show closed questions',
    [LocalizationKey.SelectActiveQuestion]: 'Select current question',
    [LocalizationKey.SendingActiveQuestion]: 'Sending current question',
    [LocalizationKey.CreatingRoomQuestion]: 'Creating current question',
    [LocalizationKey.CategoryCreatedSuccessfully]: 'Category created successfully',
    [LocalizationKey.CategoryUpdatedSuccessfully]: 'Category updated successfully',
    [LocalizationKey.LoadingRoom]: 'Loading meeting',
    [LocalizationKey.ErrorLoadingRoom]: 'Error loading meeting',
    [LocalizationKey.LoadingRoomState]: 'Loading meeting state',
    [LocalizationKey.ErrorLoadingRoomState]: 'Error loading meeting state',
    [LocalizationKey.RoomCreated]: 'Meeting created',
    [LocalizationKey.ErrorSendingActiveQuestion]: 'Error sending current question',
    [LocalizationKey.ErrorCreatingRoomQuestion]: 'Error creating question',
    [LocalizationKey.ReactionsLoadingError]: 'Reactions loading error',
    [LocalizationKey.ErrorSendingReaction]: 'Error sending reaction',
    [LocalizationKey.GetRoomEvent]: 'Receiving meeting event',
    [LocalizationKey.ErrorGetRoomEvent]: 'Error receiving meeting event',
    [LocalizationKey.ErrorSendingRoomEvent]: 'Error sending meeting event',
    [LocalizationKey.TermsOfUsage]: 'Terms of usage',
    [LocalizationKey.Login]: 'Login',
    [LocalizationKey.LikeTable]: '👍',
    [LocalizationKey.DislikeTable]: '👎',
    [LocalizationKey.Like]: 'Like',
    [LocalizationKey.Dislike]: 'Dislike',
    [LocalizationKey.CodeEditor]: 'Code editor',
    [LocalizationKey.Question]: 'Question',
    [LocalizationKey.ActiveQuestion]: 'Current question',
    [LocalizationKey.QuestionsSummary]: 'Questions summary',
    [LocalizationKey.FailedToCalculateMark]: 'Failed to calculate mark',
    [LocalizationKey.RoomAnayticsSummary]: 'Meeting anaytics',
    [LocalizationKey.MarkNotCalculated]: 'Mark not calculated',
    [LocalizationKey.MarkWithPlus]: 'with plus',
    [LocalizationKey.MarkWithMinus]: 'witn minus',
    [LocalizationKey.MarkAveragePrefix]: 'Clear',
    [LocalizationKey.MarkAverage]: 'average',
    [LocalizationKey.MarkPostfixCool]: 'Cool.',
    [LocalizationKey.MarkPostfixAverage]: 'Average.',
    [LocalizationKey.MarkPostfixBad]: 'Bad.',
    [LocalizationKey.MarkSmmary]: 'Mark smmary',
    [LocalizationKey.CloseRoom]: 'Close meeting',
    [LocalizationKey.WaitingRoom]: 'Waiting to start.',
    [LocalizationKey.StartReviewRoom]: 'Start meeting review. 📔',
    [LocalizationKey.CloseRoomModalTitle]: 'Do you really want to close meeting?',
    [LocalizationKey.StartReviewRoomModalTitle]: 'Start filling out meeting report?',
    [LocalizationKey.CloseRoomLoading]: 'Closing meeting',
    [LocalizationKey.Yes]: 'Yes ✔️',
    [LocalizationKey.No]: 'No ❌',
    [LocalizationKey.RoomStatusNew]: 'Waiting to start',
    [LocalizationKey.RoomStatusActive]: 'Active',
    [LocalizationKey.RoomStatusReview]: 'Review',
    [LocalizationKey.RoomStatusClose]: 'Close',
    [LocalizationKey.Reviews]: 'Reviews',
    [LocalizationKey.AddReview]: 'Add review',
    [LocalizationKey.AddReviewPlaceholder]: 'Write a review here',
    [LocalizationKey.Send]: 'Send',
    [LocalizationKey.WithLove]: 'WithLove',
    [LocalizationKey.TagsPlaceholder]: 'Select tags',
    [LocalizationKey.TagsLoading]: 'Loading tags',
    [LocalizationKey.NoTags]: 'No tags',
    [LocalizationKey.SearchByTags]: 'Search by tags',
    [LocalizationKey.BuildHash]: 'Build',
    [LocalizationKey.CreateRoom]: 'Create meeting',
    [LocalizationKey.NewRoom]: 'New room',
    [LocalizationKey.AddingRoomQuestions]: 'Adding Interview Questions',
    [LocalizationKey.CreatingRoom]: 'Creating meeting',
    [LocalizationKey.CreateRoomStep1]: 'Step 1 - Filling the Room',
    [LocalizationKey.CreateRoomStep2]: 'Step 2 - Inviting Participants',
    [LocalizationKey.RoomName]: 'Meeting name',
    [LocalizationKey.RoomNamePrompt]: 'In the title, indicate the name of the candidate and the position for which the interview will be held',
    [LocalizationKey.RoomDateAndTime]: 'Date and time',
    [LocalizationKey.RoomQuestions]: 'Questions list',
    [LocalizationKey.RoomSelectedQuestions]: 'Selected questions',
    [LocalizationKey.AddRoomQuestions]: 'Add questions',
    [LocalizationKey.RoomParticipants]: 'Participants',
    [LocalizationKey.RoomExperts]: 'Experts',
    [LocalizationKey.RoomExaminees]: 'Examinees',
    [LocalizationKey.SearchByValue]: 'Search by value',
    [LocalizationKey.Recognized]: '🗣️',
    [LocalizationKey.UserStreamError]: 'Unable to access camera and microphone',
    [LocalizationKey.ChatWelcomeMessage]: 'Welcome to chat',
    [LocalizationKey.ChatWelcomeMessageNickname]: 'System',
    [LocalizationKey.ChatMessagePlaceholder]: 'Write to chat',
    [LocalizationKey.SendToChat]: 'Send',
    [LocalizationKey.SearchByName]: 'Search by name',
    [LocalizationKey.ParticipatingRooms]: 'I\'m participating',
    [LocalizationKey.RootCategories]: 'Root categories',
    [LocalizationKey.Category]: 'Category',
    [LocalizationKey.SelectCategorySubcategory]: 'Select category and subcategory',
    [LocalizationKey.ClosedRooms]: 'Closed',
    [LocalizationKey.ToRooms]: 'Go to meetings',
    [LocalizationKey.Warning]: 'WARNING!',
    [LocalizationKey.CallRecording]: 'The conversation is being recorded',
    [LocalizationKey.VoiceRecognitionNotSupported]: 'Voice recognition is not supported by your browser',
    [LocalizationKey.VoiceRecognition]: 'Transcription',
    [LocalizationKey.Archive]: 'Archive',
    [LocalizationKey.ArchiveLoading]: 'Archiving...',
    [LocalizationKey.NoQuestionsSelector]: 'No questions available',
    [LocalizationKey.Join]: 'Join',
    [LocalizationKey.JoiningRoom]: 'Joining meeting',
    [LocalizationKey.JoinAs]: 'Join as',
    [LocalizationKey.SetupDevices]: 'Set up camera and microphone',
    [LocalizationKey.Camera]: 'Camera',
    [LocalizationKey.Microphone]: 'Mic',
    [LocalizationKey.Settings]: 'Settings',
    [LocalizationKey.Chat]: 'Chat',
    [LocalizationKey.ScreenShare]: 'Screen share',
    [LocalizationKey.Exit]: 'Leave',
    [LocalizationKey.ChatTab]: 'Chat',
    [LocalizationKey.RecognitionTab]: 'Transcription',
    [LocalizationKey.Theme]: 'Theme',
    [LocalizationKey.ThemeSystem]: 'System',
    [LocalizationKey.ThemeLight]: 'Light',
    [LocalizationKey.ThemeDark]: 'Dark',
    [LocalizationKey.Language]: 'Language',
    [LocalizationKey.FontSize]: 'FontSize',
    [LocalizationKey.You]: 'You',
    [LocalizationKey.NoRecords]: 'No records',
    [LocalizationKey.ConnectionError]: 'Connection error',
    [LocalizationKey.RoomConnectionError]: 'Connection to the room has been lost',
    [LocalizationKey.LocalizationLangEn]: 'English',
    [LocalizationKey.LocalizationLangRu]: 'Русский',
    [LocalizationKey.AiAssistantName]: 'Michael (Alpha)',
    [LocalizationKey.AiAssistantWelcomePrompt]: 'Hi Michael',
    [LocalizationKey.ErrorApplyRoomInvite]: 'Meeting invitation is invalid',
    [LocalizationKey.RoomInvitesLoading]: 'Loading room invites',
    [LocalizationKey.Invitations]: 'Invitations',
    [LocalizationKey.InviteViaLink]: 'Invite via link',
    [LocalizationKey.RefreshAll]: 'Refresh all',
    [LocalizationKey.NextRoomQuestion]: 'Next question',
    [LocalizationKey.CopiedToClipboard]: 'Copied to clipboard',
  },
  [LocalizationLang.ru]: {
    [LocalizationKey.SpeechRecognitionLang]: 'ru',
    [LocalizationKey.AppName]: 'Interview Platform',
    [LocalizationKey.AppDescription]: 'Интерактивная платформа для проведения собеседований с возможностью составления детальных отчётов.',
    [LocalizationKey.WelcomeMessage]: 'Добро пожаловать',
    [LocalizationKey.CurrentRoomsPageName]: 'Актуальные комнаты',
    [LocalizationKey.ClosedRoomsPageName]: 'Завершенные комнаты',
    [LocalizationKey.RoomsPageName]: 'Встречи',
    [LocalizationKey.QuestionsPageName]: 'Вопросы',
    [LocalizationKey.CategoriesPageName]: 'Категории',
    [LocalizationKey.UnauthorizedMessage]: 'Неавторизован',
    [LocalizationKey.Page]: 'Страница',
    [LocalizationKey.LogOut]: 'Выйти',
    [LocalizationKey.Edit]: 'Редактировать',
    [LocalizationKey.Viewer]: 'Зритель',
    [LocalizationKey.Viewers]: 'Зрители',
    [LocalizationKey.Expert]: 'Собеседующий',
    [LocalizationKey.Examinee]: 'Собеседуемый',
    [LocalizationKey.Save]: 'Сохранить',
    [LocalizationKey.CreateQuestion]: 'Создать вопрос',
    [LocalizationKey.QuestionText]: 'Текст вопроса',
    [LocalizationKey.QuestionType]: 'Тип вопроса',
    [LocalizationKey.QuestionTypePrivate]: 'Личный',
    [LocalizationKey.QuestionCodeEditor]: 'Код к вопросу',
    [LocalizationKey.QuestionAddCodeEditor]: 'Добавить код вопроса',
    [LocalizationKey.QuestionRemoveCodeEditor]: 'Удалить код',
    [LocalizationKey.QuestionAnswerOptions]: 'Варианты ответа',
    [LocalizationKey.QuestionAddAnswerOption]: 'Добавить вариант ответа',
    [LocalizationKey.QuestionDeleteAnswerOption]: 'Удалить вариант ответа',
    [LocalizationKey.QuestionAnswerOptionName]: 'Название варианта ответа',
    [LocalizationKey.QuestionTypePublic]: 'Публичный',
    [LocalizationKey.CreateCategory]: 'Создать категорию',
    [LocalizationKey.CategoryName]: 'Имя категории',
    [LocalizationKey.CategoryParent]: 'Родительская категория',
    [LocalizationKey.Create]: 'Создать',
    [LocalizationKey.Continue]: 'Дальше',
    [LocalizationKey.Cancel]: 'Отменить',
    [LocalizationKey.Error]: 'Ошибка',
    [LocalizationKey.NotSelected]: 'Не выбрано',
    [LocalizationKey.QuestionCreatedSuccessfully]: 'Вопрос успешно создан',
    [LocalizationKey.QuestionUpdatedSuccessfully]: 'Вопрос успешно обновлён',
    [LocalizationKey.ShowClosedQuestions]: 'Показывать закрытые вопросы',
    [LocalizationKey.SelectActiveQuestion]: 'Установить текущий вопрос',
    [LocalizationKey.SendingActiveQuestion]: 'Установка вопроса',
    [LocalizationKey.CreatingRoomQuestion]: 'Создание текущего вопроса',
    [LocalizationKey.CategoryCreatedSuccessfully]: 'Категория успешно создана',
    [LocalizationKey.CategoryUpdatedSuccessfully]: 'Категория успешно обновлёна',
    [LocalizationKey.LoadingRoom]: 'Загрузка встречи',
    [LocalizationKey.ErrorLoadingRoom]: 'Ошибка загрузки встречи',
    [LocalizationKey.LoadingRoomState]: 'Загрузка состояния встречи',
    [LocalizationKey.ErrorLoadingRoomState]: 'Ошибка загрузки состояния встречи',
    [LocalizationKey.RoomCreated]: 'Встреча успешно создана',
    [LocalizationKey.ErrorSendingActiveQuestion]: 'Ошибка в установке вопроса',
    [LocalizationKey.ErrorCreatingRoomQuestion]: 'Ошибка создания текущего вопроса',
    [LocalizationKey.ReactionsLoadingError]: 'Ошибка загрузки реакций',
    [LocalizationKey.ErrorSendingReaction]: 'Ошибка в отправке реакции',
    [LocalizationKey.GetRoomEvent]: 'Получение событий',
    [LocalizationKey.ErrorGetRoomEvent]: 'Ошибка в получении событий',
    [LocalizationKey.ErrorSendingRoomEvent]: 'Ошибка в отправке собтия',
    [LocalizationKey.TermsOfUsage]: 'Условия использования',
    [LocalizationKey.Login]: 'Войти',
    [LocalizationKey.LikeTable]: '👍',
    [LocalizationKey.DislikeTable]: '👎',
    [LocalizationKey.Like]: 'Хорошо',
    [LocalizationKey.Dislike]: 'Плохо',
    [LocalizationKey.CodeEditor]: 'Редактор кода',
    [LocalizationKey.Question]: 'Вопрос',
    [LocalizationKey.ActiveQuestion]: 'Текущий вопрос',
    [LocalizationKey.QuestionsSummary]: 'Отчёт по воросам',
    [LocalizationKey.FailedToCalculateMark]: 'Ошибка при подсчёте оценки',
    [LocalizationKey.RoomAnayticsSummary]: 'Анадитика по встрече',
    [LocalizationKey.MarkNotCalculated]: 'Оценка не рассчитана',
    [LocalizationKey.MarkWithPlus]: 'с плюсом',
    [LocalizationKey.MarkWithMinus]: 'с минусом',
    [LocalizationKey.MarkAveragePrefix]: 'Средне',
    [LocalizationKey.MarkAverage]: 'средне',
    [LocalizationKey.MarkPostfixCool]: 'Круто.',
    [LocalizationKey.MarkPostfixAverage]: 'Средне.',
    [LocalizationKey.MarkPostfixBad]: 'Плохо.',
    [LocalizationKey.MarkSmmary]: 'Итог',
    [LocalizationKey.CloseRoom]: 'Закрыть встречу',
    [LocalizationKey.WaitingRoom]: 'Ожидание начала встречи',
    [LocalizationKey.StartReviewRoom]: 'Начать разбор встречи',
    [LocalizationKey.CloseRoomModalTitle]: 'Действительно хотите закрыть встречу?',
    [LocalizationKey.StartReviewRoomModalTitle]: 'Начать заполнение отчёта по встрече?',
    [LocalizationKey.CloseRoomLoading]: 'Закрытие встречи',
    [LocalizationKey.Yes]: 'Да ✔️',
    [LocalizationKey.No]: 'Нет ❌',
    [LocalizationKey.RoomStatusNew]: 'Ожидание начала',
    [LocalizationKey.RoomStatusActive]: 'Идёт встреча',
    [LocalizationKey.RoomStatusReview]: 'Разбор',
    [LocalizationKey.RoomStatusClose]: 'Закрыта',
    [LocalizationKey.Reviews]: 'Отзывы',
    [LocalizationKey.AddReview]: 'Написать отзыв',
    [LocalizationKey.AddReviewPlaceholder]: 'Написать отзыв',
    [LocalizationKey.Send]: 'Отправить',
    [LocalizationKey.WithLove]: 'С любовью',
    [LocalizationKey.TagsPlaceholder]: 'Выбрать тэги',
    [LocalizationKey.TagsLoading]: 'Загрузка тэгов',
    [LocalizationKey.NoTags]: 'Тэги отсутствуют',
    [LocalizationKey.SearchByTags]: 'Поиск по тэгам',
    [LocalizationKey.BuildHash]: 'Сборка',
    [LocalizationKey.CreateRoom]: 'Создать встречу',
    [LocalizationKey.NewRoom]: 'Новая комната',
    [LocalizationKey.AddingRoomQuestions]: 'Добавление вопросов для собеседования',
    [LocalizationKey.CreatingRoom]: 'Создание встречи',
    [LocalizationKey.CreateRoomStep1]: 'Шаг 1 - Наполнение комнаты',
    [LocalizationKey.CreateRoomStep2]: 'Шаг 2 - Приглашение участников',
    [LocalizationKey.RoomName]: 'Имя встречи',
    [LocalizationKey.RoomNamePrompt]: 'В названии укажите имя кандидата и должность, на которую пройдет собеседование',
    [LocalizationKey.RoomDateAndTime]: 'Дата и время',
    [LocalizationKey.RoomQuestions]: 'Список вопросов',
    [LocalizationKey.RoomSelectedQuestions]: 'Выбрано вопросов',
    [LocalizationKey.AddRoomQuestions]: 'Добавить вопросы',
    [LocalizationKey.RoomParticipants]: 'Участники',
    [LocalizationKey.RoomExperts]: 'Собеседующие',
    [LocalizationKey.RoomExaminees]: 'Собеседуемые',
    [LocalizationKey.SearchByValue]: 'Поиск по содержимому',
    [LocalizationKey.Recognized]: '🗣️',
    [LocalizationKey.UserStreamError]: 'Не удалось получить доступ к камере и микрофону',
    [LocalizationKey.ChatWelcomeMessage]: 'Добро пожаловать',
    [LocalizationKey.ChatWelcomeMessageNickname]: 'Система',
    [LocalizationKey.ChatMessagePlaceholder]: 'Написать в чат',
    [LocalizationKey.SendToChat]: 'Чат',
    [LocalizationKey.SearchByName]: 'Поиск по имени',
    [LocalizationKey.ParticipatingRooms]: 'Я участвую',
    [LocalizationKey.RootCategories]: 'Корневые категории',
    [LocalizationKey.Category]: 'Категория',
    [LocalizationKey.SelectCategorySubcategory]: 'Выберите категорию и подкатегорию',
    [LocalizationKey.ClosedRooms]: 'Закрытые',
    [LocalizationKey.ToRooms]: 'Перейти ко встречам',
    [LocalizationKey.Warning]: 'ВНИМАНИЕ!',
    [LocalizationKey.CallRecording]: 'Разговор записыватеся',
    [LocalizationKey.VoiceRecognitionNotSupported]: 'Распознавание голоса не поддерживается вашим браузером',
    [LocalizationKey.VoiceRecognition]: 'Транскрипция',
    [LocalizationKey.Archive]: 'В архив',
    [LocalizationKey.ArchiveLoading]: 'Ахивирование...',
    [LocalizationKey.NoQuestionsSelector]: 'Нет доступных вопросов',
    [LocalizationKey.Join]: 'Присоединиться',
    [LocalizationKey.JoiningRoom]: 'Подключение ко встрече',
    [LocalizationKey.JoinAs]: 'Подключиться как',
    [LocalizationKey.SetupDevices]: 'Настроить камеру и микрофон',
    [LocalizationKey.Camera]: 'Камера',
    [LocalizationKey.Microphone]: 'Аудио',
    [LocalizationKey.Settings]: 'Настройки',
    [LocalizationKey.Chat]: 'Чат',
    [LocalizationKey.ScreenShare]: 'Демонстрация',
    [LocalizationKey.Exit]: 'Выйти',
    [LocalizationKey.ChatTab]: 'Чат',
    [LocalizationKey.RecognitionTab]: 'Транскрипция',
    [LocalizationKey.Theme]: 'Тема оформления',
    [LocalizationKey.ThemeSystem]: 'Системная',
    [LocalizationKey.ThemeLight]: 'Светлая',
    [LocalizationKey.ThemeDark]: 'Тёмная',
    [LocalizationKey.Language]: 'Язык',
    [LocalizationKey.FontSize]: 'Размер шрифта',
    [LocalizationKey.You]: 'Вы',
    [LocalizationKey.NoRecords]: 'Нет записей',
    [LocalizationKey.ConnectionError]: 'Ошибка подключения',
    [LocalizationKey.RoomConnectionError]: 'Соединение с комнатой потеряно',
    [LocalizationKey.LocalizationLangEn]: 'English',
    [LocalizationKey.LocalizationLangRu]: 'Русский',
    [LocalizationKey.AiAssistantName]: 'Михаил (Альфа)',
    [LocalizationKey.AiAssistantWelcomePrompt]: 'Привет Михаил',
    [LocalizationKey.ErrorApplyRoomInvite]: 'Приглашение на встречу недействительно',
    [LocalizationKey.RoomInvitesLoading]: 'Загрузка приглашений в комнату',
    [LocalizationKey.Invitations]: 'Приглашения',
    [LocalizationKey.InviteViaLink]: 'Пригласить по ссылке',
    [LocalizationKey.RefreshAll]: 'Обновить все',
    [LocalizationKey.NextRoomQuestion]: 'Следующий вопрос',
    [LocalizationKey.CopiedToClipboard]: 'Скопировано в буфер обмена',
  },
}
